spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3308/petlog}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties.hibernate.format_sql: true

jwt:
  issuer: petlog2025@gmail.com
  secret_key: petlog-project-2025
